name: CI and Docker CD

on:
  push:
    branches:
      - dev
      - stable
    paths-ignore:
      - .github/*
      - .vscode/*
      - .gitignore
  pull_request:
    branches:
      - dev
      - stable
    paths-ignore:
      - .github/*
      - .vscode/*
      - .gitignore
  workflow_dispatch:

jobs:
  build-and-push-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Optional: Get version from version.py for tagging 'stable' builds
      # - name: Extract version
      #   id: get_version
      #   if: github.ref == 'refs/heads/stable' && github.event_name == 'push' # Only needed for stable pushes if version tagging is desired
      #   run: |
      #     APP_VERSION=$(python -c "from version import __version__; print(__version__)")
      #     echo "APP_VERSION=${APP_VERSION}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: nokodo/twitchdropsminer
          # Define tagging strategy:
          # - 'dev' tag for pushes to the 'dev' branch
          # - 'latest' tag for pushes to the 'stable' branch
          # - Optional: Version tag (e.g., 1.2.3) for pushes to stable branch
          tags: |
            type=ref,event=branch,prefix=,suffix=,enable=${{ github.ref == 'refs/heads/dev' }}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/stable' }}
            # Uncomment below to also add version tag (e.g., v1.2.3) for stable pushes
            # Needs the 'Extract version' step above to be uncommented too
            # type=raw,value=${{ steps.get_version.outputs.APP_VERSION }},enable=${{ github.ref == 'refs/heads/stable' && github.event_name == 'push' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/386
          # Only push if it's a push event (not PR) to dev or stable
          push: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/stable') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          pull: true
          cache-from: type=gha
          cache-to: type=gha,mode=max