name: Upstream to PR

on:
    schedule:
        - cron: "0 0 * * *" # Runs every day at midnight
    workflow_dispatch:

jobs:
    upstream-sync:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Upstream to PR
              uses: fopina/upstream-to-pr@v1
              with:
                  token: ${{ secrets.UPSTREAM_TO_PR_TOKEN }}
                  upstream-repository: https://github.com/devilxd/twitchdropsminer.git
                  upstream-branch: master
                  keep-old: false
                  reviewers: Davixk
