name: Upstream to PR

on:
    schedule:
        - cron: "0 0 * * *" # Runs every day at midnight
    workflow_dispatch:

jobs:
    upstream-sync:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: DevilXD Upstream to PR
              uses: fopina/upstream-to-pr@v1
              with:
                  token: ${{ secrets.UPSTREAM_TO_PR_TOKEN }}
                  upstream-repository: https://github.com/devilxd/twitchdropsminer.git
                  upstream-branch: master
                  keep-old: false
                  reviewers: Davixk
            
            # - name: Windows200000 Upstream to PR
            #   uses: fopina/upstream-to-pr@v1
            #   with:
            #       token: ${{ secrets.UPSTREAM_TO_PR_PAT }}
            #       upstream-repository: https://github.com/Windows200000/TwitchDropsMiner-updated.git
            #       upstream-branch: master
            #       keep-old: false
            #       reviewers: Davixk
            
            # - name: fireph Upstream to PR
            #   uses: fopina/upstream-to-pr@v1
            #   with:
            #       token: ${{ secrets.UPSTREAM_TO_PR_PAT }}
            #       upstream-repository: https://github.com/fireph/TwitchDropsMiner-Alpine.git
            #       upstream-branch: master
            #       keep-old: false
            #       reviewers: Davixk